### ISSUE TITLE
Predator 228 throws an error

### ISSUE THREAD

**Issue by sliterok** [hobbyquaker/arcticfox#1]
You can also replicate it on windows 10

TypeError: Cannot read property 'write' of null
    at ArcticFox.hidWrite (/home/mint/arcticfox/arcticfox-config/node_modules/arcticfox/index.js:192:21)
    at ArcticFox.readConfiguration (/home/mint/arcticfox/arcticfox-config/node_modules/arcticfox/index.js:1102:18)
    at EventEmitter.ipc.on (/home/mint/arcticfox/arcticfox-config/main.js:127:9)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at WebContents.<anonymous> (/home/mint/arcticfox/arcticfox-config/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

**Comment by hobbyquaker** [comment]
I guess you ran into this bug when using https://github.com/hobbyquaker/arcticfox-config ? If yes - could you retry with the latest release (v1.9.0-beta.0)?

**Comment by sliterok** [comment]
On my windows 10, using the latest release node throws an timeout error with successful connect event.

```
connect
Error: timeout
    at Timeout.timeout.setTimeout [as _onTimeout] (D:\workspace\arct\arct2\index.js:1141:26)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)`
```

**Comment by sliterok** [comment]
I might try this using RX 2/3 of my friend tomorrow.

**Comment by hobbyquaker** [comment]
Ok. I would prefer Issues to be reported on https://github.com/hobbyquaker/arcticfox-config/issues - if it's ok for you I'd close this one and ask you to open a new one on the arcticfox-config issue tracker.

**Comment by sliterok** [comment]
Oh no, i can't use arcticfox-config on windows 10 machine, it throws some HID lib error. Probably i've just reported another issue above
